import type { NextPage } from 'next';
import Head from 'next/head';
import { Header } from '../components/header';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Supacode.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
};

export default Home;
