#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '❌❌❌ Invalid code format.❌❌❌ 
        Prettier Check failed. Run `npm run format`, add changes and try again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '❌ Type checking failed! 
                ESLint Check Failed. Double check your code and try commit again.';
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check. ❌
            Make the changes required above.'
    false;
)

# Check SCSS Standards
npm run lint:scss ||
(
    echo '❌ Error linting SCSS ❌
            Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🏿🔨❌ Build failed. ❌👷🏿🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅ Every looks Ok. ✅✅✅'



